services:
  pingvin-share:
    container_name: app-rtransfer
    build: .
    restart: unless-stopped
    ports:
      - 3011:3000
    environment:
      - TRUST_PROXY=false
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
      - "./config.yaml:/opt/app/config.yaml"
    networks:
      - ldap_my_custom_network

networks:
  ldap_my_custom_network:
    external: true
